config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

  root 'welcome#index'
 end
 

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def index
    @comments = @post.comments
    # render :json => @comments
    # render layout: false
    respond_to do |format|
      format.html {render 'index.html', layout: false}
      format.js {render 'index.js', layout: false}
    end 
  end

  def show 
    @comment = Comment.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:post_id])
  end

  def create
    @comment = @post.comments.new(comment_params)    
    if @comment.save
      # render 'comments/show_comment', layout: false
      render 'create.js', layout: false 
    else
      render 'posts/show'
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def set_post 
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end
 
  def show
    @comments = @post.comments
    @comment = Comment.new(post_id: @post.id)
  end
 
  def new
    @post = Post.new
  end
 
  def edit
  end
 
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
 
  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
 
  def destroy
    @post.destroy
    redirect_to posts_path
  end
 
  private
    def set_post 
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved: 
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </p>

  <p>
    <%= f.submit %> 
  </p>

<% end %>

app/views/comments/_comment.html.erb
<li><%= comment.content %> created: <%= comment.created_at %></li>

app/views/comments/_comments.html.erb
<ol>
  <% @comments.each do |comment| %> 
    <li><%= comment.content %> created: <%= comment.created_at %></li>
  <% end %>
</ol>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/create.js.erb
$('#comment_content').val('')
$("div.comments ol").append("<%= j(render('comments/comment', comment: @comment)) %>")

app/views/comments/edit.html.erb
<%= form_for([@post, @post.comments]) do |f| %>
<p>
  <%= f.label :content %><br>
  <%= f.text_area :content %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/comments/index.html.erb
<ul>
  <% @comments.each do |comment| %>
  <li><%= comment.content %></li>
  <% end %>
</ul>

app/views/comments/index.js.erb
let html = "<%= j render 'comment' %>"

$('div#comments').append(html)

app/views/comments/index1.js.erb
let html = "<%= j render 'comment' %>"

$('div#comments').append(html)

app/views/comments/indexJS.html.erb
let html = "<%= j render 'comment' %>"

$('div#comments').append(html)

app/views/comments/show_comment.html.erb
<li><%= @comment.content %> created: <%= @comment.created_at %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'jquery-3.2.1.min.js' %>
  <%= javascript_include_tag 'ajax-video2' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved: 
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>

  <p>
    <%= f.submit %> 
  </p>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
<%= link_to 'New post', new_post_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure, are you ok???' } %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:
  <%= @post.title %></strong>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<strong>Comments: </strong>
<div class="comments">
  <%= render 'comments/comments' %>
</div>

<strong>Add comment:</strong>
<!-- <%#= form_for(@comment, url: post_comments_path(@post)) do |f| %> -->

<%= form_for([@post, @comment], remote: true) do |f| %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

  <!-- <form id="new-comment" action="<%#= post_comments_path(@post, @comment) %>">
    <p>Commenter: <input type="text" id="commenter"></p>
    <p>Body: <input type="textarea" id="body"></p>
    <p><input type="submit"></p>
  </form> -->

<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'All posts', controller: 'posts' %>
<%= link_to 'New post', new_post_path %>